platform :ios, '13.0'
use_frameworks!

install! 'cocoapods', :warn_for_unused_master_specs_repo => false

workspace 'zkSync-Demo'

project 'zkSync-Demo.xcodeproj'
project '../../Sources/ZkSync2/ZkSync2.xcodeproj'

target 'ZkSync2' do
  project '../../Sources/ZkSync2/ZkSync2.xcodeproj'
  
  pod 'BigInt', '5.2.0'
  pod 'Alamofire', '5.7.1'
  pod 'CryptoSwift', '1.4.3'
  pod 'PromiseKit', '6.15.3'
  pod 'Starscream', '4.0.4'
  pod 'secp256k1.c', '0.1.2'
  pod 'web3swift-zksync', :git => 'https://github.com/zksync-sdk/web3swift.git', :branch => 'v2.6.5-zksync'
end

target 'zkSync-Demo' do
  project 'zkSync-Demo.xcodeproj'
  
  pod 'BigInt', '5.2.0'
  pod 'Alamofire', '5.7.1'
  pod 'CryptoSwift', '1.4.3'
  pod 'PromiseKit', '6.15.3'
  pod 'Starscream', '4.0.4'
  pod 'secp256k1.c', '0.1.2'
  pod 'web3swift-zksync', :git => 'https://github.com/zksync-sdk/web3swift.git', :branch => 'v2.6.5-zksync'
end
