platform :ios, '13.0'
use_frameworks!

install! 'cocoapods', :warn_for_unused_master_specs_repo => false

workspace 'zkSync-Demo'

project 'zkSync-Demo.xcodeproj'

def project_pods
  pod 'BigInt', '5.2.0'
  pod 'Alamofire', '5.7.1'
  pod 'PromiseKit', '6.15.3'
  pod 'Starscream', '4.0.4'
  pod 'secp256k1.c', '0.1.2'
  pod 'web3swift', '3.1.2'
end

target 'zkSync-Demo-Localhost' do
  project 'zkSync-Demo.xcodeproj'
  
  project_pods
end

target 'zkSync-Demo-Testnet' do
  project 'zkSync-Demo.xcodeproj'
  
  project_pods
end
