# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  workflow_dispatch:
  pull_request:
    branches: main
    types: [ opened, reopened, synchronize ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v
    - name: Run local-setup
        run: |
          git clone https://github.com/matter-labs/local-setup.git
          pushd local-setup
          docker-compose up -d
          popd
    - name: Wait until server is up
        run: |
          while ! curl -s -X POST -d '{"jsonrpc":"2.0","method":"net_version","id":1}' -H 'Content-Type: application/json' 0.0.0.0:3050; do sleep 1; done
    - name: Run tests
      run: swift test --skip-build --very-verbose --filter EIP712EncoderTests --skip EIP712EncoderTests.testEncodeDomainMemberValues;
           swift test --skip-build --very-verbose --filter Transaction712Tests --skip Transaction712Tests.testSerializeToEIP712Message;
           swift test --skip-build --very-verbose --filter ContractDeployerTests;
           swift test --skip-build --very-verbose --filter EthereumKeystoreV3Tests;
           swift test --skip-build --very-verbose --filter ZKSyncWeb3RpcIntegrationTests;
           swift test --skip-build --very-verbose --filter ZkSyncWalletIntegrationTests;

           
